baseURL = ""
relativeURLS = true
title   = "Mahasemesta"
languageCode = "en-us"
theme = "akasha"

summaryLength = 20
paginate  = 5

PygmentsCodeFences = true
PygmentsStyle = "monokai"

disqusShortname = "https-mahasemesta-xyz"
googleAnalytics = "G-YNRC5F8LG5"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  journey = "/journey/:title/"

[author]
  name = "Mahasemesta"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  category = "categories"
  
[params]

  home1 = "Mahasemesta Hypnotherapy"
  home2 = "Heal you past to embrace your future"
  home_button = "TOUCH THE CAT TO BEGIN"

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  disableReadOtherPosts = false
  enableSharingButtons = false

  defaultTheme = "dark"
  themeColor = "#1b1c1d"

[menu]
    [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "services/"
    weight = "1"

    [[menu.main]]
    identifier = "journey"
    name = "Journey"
    url = "journey/"
    weight = "2"

    [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "contact/"
    weight = "3"   