baseURL = ""
relativeURLS = true
title   = "Mahasemesta"
languageCode = "en-us"

summaryLength = 20
paginate  = 5

PygmentsCodeFences = true
PygmentsStyle = "monokai"

# disqusShortname = "https-mahasemesta-xyz"
# googleAnalytics = "G-YNRC5F8LG5"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  blog = "/blog/:title/"

[author]
  name = "Mahasemesta"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  kategori = "kategori"
  
[params]

  keyword = "mahasemesta, hipnoterapi, hipnosis, hipnotis"

  homeSubtitle = "Heal you past to embrace your future"
  homeButton = "INTRODUCTION"

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  disableReadOtherPosts = false
  enableSharingButtons = false

  defaultTheme = "dark"
  themeColor = "#1b1c1d"

[menu]
    [[menu.main]]
    identifier = "terapi"
    name = "Terapi"
    url = "terapi/"
    weight = "1"

    [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "blog/"
    weight = "2"

    [[menu.main]]
    identifier = "kontak"
    name = "Kontak"
    url = "kontak/"
    weight = "3"