baseURL = ""
relativeURLS = true
title   = "Mahasemesta"
languageCode = "en-us"
theme = ["akasha", "hugo-search-fuse-js"]

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10

disqusShortname = "https-mahasemesta-xyz"
googleAnalytics = "G-YNRC5F8LG5"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = false
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Mahasemesta"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  category = "categories"
  
[params]

  footer = "Mahasemesta"
  home1 = "Mahasemesta Hypnotherapy"
  home2 = "Heal you past to embrace your future"
  home_button = "TOUCH THE CAT TO BEGIN"

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Hello Friend NG"
  disableReadOtherPosts = false
  enableSharingButtons = false

  defaultTheme = "dark"
  themeColor = "#1b1c1d"

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoCursorColor    = "#67a2c9"
    logoCursorAnimate  = "2s"

[menu]
    [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "services/"
    weight = "1"

    [[menu.main]]
    identifier = "journey"
    name = "Journey"
    url = "journey/"
    weight = "2"

    [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "contact/"
    weight = "3"

    [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "search/"
    weight = "4"